package com.mbh.initio.diagnostic;

public enum DiagnosticRuleId {
	MISSING_RUNTIME,
	INCOMPATIBLE_RUNTIME,
	MISSING_ENVIRONMENT_VARIABLE,
	DOCKER_UNAVAILABLE,
	MISSING_REQUIRED_SERVICE,
	PORT_CONFLICT,
	DECLARATION_DRIFT
}
